version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    restart: unless-stopped
    volumes:
      - media:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - .env.${ENV:-local}
      - .env

  db:
    image: postgres:15
    env_file:
      - .env.${ENV:-local}
      - .env
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST_DOMAIN: usersnack.dammy.co
      REVERSE_PROXY_TO: app:8000
      MEDIA_ROOT: /var/media
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - media:/var/media

volumes:
  media:
  postgres_data:
